2018-02-06 12:24:43,975 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 40, in create_post
    if g.current_user.id != data['user_id']:
NameError: global name 'g' is not defined
2018-02-06 12:28:14,928 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:28:29,041 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 43, in create_post
    db.session.add(post)
NameError: global name 'db' is not defined
2018-02-06 12:28:54,306 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:28:58,588 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 48, in create_post
    response.headers['Location'] = url_for('api.get_post', id=post.id)
NameError: global name 'url_for' is not defined
2018-02-06 12:29:11,037 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:36:04,777 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:36:10,457 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 41, in create_post
    current_user = User.check_token(token)
NameError: global name 'token' is not defined
2018-02-06 12:38:11,383 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:39:53,727 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 12:39:58,661 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 45, in create_post
    g.current_user = User.check_token(token)
NameError: global name 'token' is not defined
2018-02-06 13:35:27,883 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 15:51:14,839 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 15:51:45,606 ERROR: Exception on /api/posts [POST] [in /Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rlheureu/Coding/microblog-0.15/venv/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/Users/rlheureu/Coding/microblog-0.15/app/api/posts.py", line 45, in create_post
    user= User.query.filter_by(token=token).first()
NameError: global name 'token' is not defined
2018-02-06 15:55:46,308 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 15:55:54,889 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 16:00:03,476 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
2018-02-06 16:00:53,967 INFO: Microblog startup [in /Users/rlheureu/Coding/microblog-0.15/app/__init__.py:85]
